### ISSUE TITLE
보안키 작업 비밀번호 확인 

### ISSUE THREAD

**Issue by kd02109** [ToyVallet/swifty-bank-frontend#46]
## TODO

- [x] 비밀번호 입력칸 개수를 받을 수 있도록 구성합니다. 
- [x] 보안키 입력이 완료되면 자동으로 보안키 체크, 페이지 이동이 발생해야 합니다. 
- [x] 보안키는 서버에서 받은 이차원 SVG 배열을 바탕으로 구성합니다. 
- [x] 해당 키를 클릭, 탭 하였을 때, 물결 무늬 에니메이션이 발생해야 합니다. 
- [x] 탭, 클릭 하였을 때, 자동으로 칸이 채워지도록 합니다.
- [x] 비밀번호 입력 중 페이지 이동이 발생했을 때, 모든 입력된 비밀번호를 초기화 합니다. 
- [x] 비밀번호 확인에 실패 했을 경우 일치여부를 프런트에서 확인합니다. 

```tsx
export interface CreateKeypad {
  uid: string;
  keypad: {
    functionKeys: Array<{
      symbol: string;
      rowIndex: number;
      columnIndex: number;
    }>;
    size: {
      rows: number;
      columns: number;
    };
    svgGrid: string[][];
  };
}
```
